### PR TITLE
Prevent circular import of httplib2 before it can be installed with distribute/setuptools.

### PR DESCRIPTION
**Pull request by junkafarian**
Sorry, I misdiagnosed the problem causing the install to fail. It was due to a circular import of httplib2 when finding the version number for the setup.py script. This should _really_ fix the issue (or at least it installs properly locally).

### CODE REVIEW

**Comment by robhudson** [comment]
That makes sense. I was in a virtualenv that had it already so I didn't catch this.

**Comment by robhudson** [comment]
I'm going to tweak this and simply remove the `from pivotal import Pivotal` in `__init__.py`, which is causing it to fail.  I don't recall why I added that originally but I don't like it.  I prefer to do that import in my code that's using the Pivotal class.

**Comment by junkafarian** [comment]
No problem, will adjust in `bushy` to import from the full path.

**Comment by robhudson** [comment]
I pushed a 0.1.3 to pypi. Let me know if that clears it up.  And thanks for the heads up.

**Comment by junkafarian** [comment]
Yup, http://pypi.python.org/pypi/bushy/0.2.5 installs clean now. Many thanks for the help and swift replies.

**Pull request merged**
