### PR TITLE
Add htmllib2 as a hard dependency

### PR DESCRIPTION
**Pull request by junkafarian**
Packages specifying pivotal-py as a dependency fail to install unless htmllib2 is already available.

### CODE REVIEW

**Comment by robhudson** [comment]
Thanks!

**Comment by junkafarian** [comment]
No worries! Reckon you could push a new version to PyPI? ;)

**Comment by robhudson** [comment]
0.1.2 pushed to pypi.

**Comment by junkafarian** [comment]
cool, much appreciated

**Pull request merged**
